### ISSUE TITLE
when using "--symprec 0.0001" , SPGLIB error: TypeError: must be real number, not str

### ISSUE THREAD

**Issue by kgmat** [hackingmaterials/robocrystallographer#31]
Hello,

   I am using latest version of robocrys and spglib, on MAC Catalina OS with Python 3.8.1

  while using from CLI, whenever I issue the command 

   `robocrys filename --symprec 0.0001`

   for POSCAR/*.vasp/*.cif and for any value of --symprec 

   Program terminates with following error from SPGLIB:

  Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/robocrys", line 11, in <module>
    load_entry_point('robocrys==0.2.1', 'console_scripts', 'robocrys')()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/robocrys/cli.py", line 190, in main
    robocrystallographer(structure, condenser_kwargs=condenser_kwargs,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/robocrys/cli.py", line 50, in robocrystallographer
    condensed_structure = sc.condense_structure(structure)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/robocrys/condense/condenser.py", line 103, in condense_structure
    sga = SpacegroupAnalyzer(structure, symprec=self.symprec)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pymatgen/symmetry/analyzer.py", line 90, in __init__
    self._space_group_data = spglib.get_symmetry_dataset(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/spglib/spglib.py", line 237, in get_symmetry_dataset
    spg_ds = spg.dataset(lattice, positions, numbers, hall_number,
TypeError: must be real number, not str

**PS: The same runs fine from Python API.**

Am i doing anything wrong?

Thanks

**Comment by utf** [comment]
Thanks for reporting this bug. I've fixed it in the latest version.

You can update using `pip install robocrys --upgrade` or via git.
