### ISSUE TITLE
 'describer' throwing errors with --no-makup, --no-mineral and --no-components

### ISSUE THREAD

**Issue by kgmat** [hackingmaterials/robocrystallographer#32]
Hello,

I am using latest version of robocrys and spglib, on MAC Catalina OS with Python 3.8.1

while using from CLI, whenever I issue the command

`robocrys filename --no-makeup`

for POSCAR/.vasp/.cif any format.

'describer' is throwing errors:
============================================
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/robocrys", line 11, in <module>
    load_entry_point('robocrys==0.2.1', 'console_scripts', 'robocrys')()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/robocrys/cli.py", line 190, in main
    robocrystallographer(structure, condenser_kwargs=condenser_kwargs,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/robocrys/cli.py", line 51, in robocrystallographer
    description = describer.describe(condensed_structure)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/robocrys/describe/describer.py", line 130, in describe
    return " ".join(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/robocrys/describe/describer.py", line 133, in <genexpr>
    if description[part] is not "")
KeyError: 'component_makeup'

**PS: this error shows up, for options --no-makeup, --no-mineral and --no-components**
** from CLI, and from Python API both**

am I doing something wrong?

Thanks

**Comment by utf** [comment]
Thanks for reporting this bug. I've fixed it in the latest version.

You can update using `pip install robocrys --upgrade` or via git.
